name: Main Workflow

on: push

jobs:
  build:
    name: Main Workflow

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install black==22.8.0

      - name: Lint with Black
        run: black app --check --verbose
